- hosts: localhost
  connection: local

  vars:
    pip_install_packages:
      - name: django
        state: latest

  tasks:
      
    - name: Install Role PIP
      local_action: command ansible-galaxy install -f geerlingguy.pip 

    - name: Applying role PIP
      command: mv ~/.ansible/roles/geerlingguy.pip ~/.ansible/roles/pwslab.pip
    #   when: not pip_exists.stat.exists
      ignore_errors: yes

    - name: Installing PIP
      include_role:
        name: pwslab.pip